### ISSUE TITLE
local position unstable (ekf2 with vision fusion)

### ISSUE THREAD

**Issue by virtualclone** [PX4/Firmware#10172]
Hi, I use ekf2 vision fusion( with motion captures system)
Sometimes, local_position/pose is correct.

But sometimes, it's uncorrect. The pose will be like this:
```
pose: 
  position: 
    x: -1.52471171309e-17
    y: 3.06921519898e-33
    z: 0.124502159655
  orientation: 
    x: 0.00153229214155
    y: 0.0453438805825
    z: 0.0199263977732
    w: -0.998771528692

```
I might reboot the px4 several times to get a correct value of local_position/pose.
What's the problem about this?
My motion capture data streaming rate is at 120Hz.
And I see that the receiving data stream rate of vision_pose/pose is only at 10Hz(in QGroundControl Analyze)
Is that the problem about the large difference between the above two data stream rate(120Hz&10Hz)?
Thanks!

flight log file:
https://logs.px4.io/plot_app?log=84096440-6f9c-4610-a5d3-8c3bc592d78e
This log file is the successful flight, because if I see that the local_position/pose is not correct, I won't let the drone take off.

ROSBag file:
https://drive.google.com/file/d/1JmP7I9GZqVxmh8uSSukeY--itedRVQMn/view?usp=sharing
the respective topic: `/drone3/mavros/local_position/pose`
You can see that the pose is very strange. The postion of x, y is very close to zero.
like this:

```
header: 
  seq: 4414
  stamp: 
    secs: 1533536785
    nsecs: 942267648
  frame_id: "map"
pose: 
  position: 
    x: -1.72637007448e-17
    y: 3.47514958151e-33
    z: 0.140968814492
  orientation: 
    x: -0.0248491935548
    y: 0.0221236218929
    z: -0.482939474001
    w: -0.875021532601

```
However at very few timestamps, it shows the correct position:
```

header: 
  seq: 4413
  stamp: 
    secs: 1533536785
    nsecs: 934267648
  frame_id: "map"
pose: 
  position: 
    x: 0.791218042374
    y: -1.84485912323
    z: 0.140622586012
  orientation: 
    x: -0.0249051236576
    y: 0.0221258913196
    z: -0.482943182924
    w: -0.875017823679

```
