### ISSUE TITLE
EKF2 vision pose aid influence the velocity estimation.

### ISSUE THREAD

**Issue by eleboss** [PX4/Firmware#10330]
**Describe the bug**
I am using VINS-mono VIO as a external vision support, and turn on the EKF2 aid, sending topic to`mavros/vision_pose/pose` at 10HZ, when the vision system works fine, the EKF2 give a relative accurate estimation.
**However, when the external vision system start to drift, the velocity estimation become very inaccurate, and may given a impossible velocity, this will directly lead to a crash in velocity control.**

Further, when I try to give a constant speed like 0.05m/s, it works well without vision aid, but shaking with vision aid, and crash when EKF velocity estimation drift with vision pose.

Inaccurate velocity feedback like that. from /mavros/local_position/odom
```
header: 
  seq: 391334
  stamp: 
    secs: 1535299548
    nsecs: 866225664
  frame_id: "map"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: -0.312624961138
      y: -4.13867712021
      z: 8.31071472168
    orientation: 
      x: 0.403164698857
      y: 0.156174051339
      z: 0.0814457080274
      w: -0.89801704281
  covariance: [1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-06]
twist: 
  twist: 
    linear: 
      x: 0.220971111536
      y: -1.39470153404
      z: -0.0521862682266
    angular: 
      x: -0.0481302216649
      y: -0.022168552503
      z: -0.00464850105345
  covariance: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0001]


```

also, when start to using the vision aid, the drone shacking more frequently, I think this may caused by the vision noise, making the total EKF velocity estimation not so accurate.

All in one, is there any way to separate the vision aid and velocity estimation? Let the vision noise not influence the velocity estimation, make the whole system more robust.

**Drone (please complete the following information):**
- Describe the type of drone.
DJI f550
- Photo of the IMU / autopilot setup if possible.
pixhawk4 with 1.8.0 stable release
