### ISSUE TITLE
UDP cannot be larger than 14550 in v1.11 SITL

### ISSUE THREAD

**Issue by robin-shaun** [PX4/Firmware#14963]
I use the same udp settings `<arg name="fcu_url" default="udp://:14551@127.0.0.1:34594"/>`, in v1.8.0 mavros connected True,  but in v1.11.0 mavros connected false.
Therefore, now I can only use 11 uavs (14540~14550) in v1.11, but in v1.8.0 I can use much more. I don't know how to solve it.
Two launch files for v1.8 and v1.11 are in the attachment.
[multi_uav_launch.zip](https://github.com/PX4/Firmware/files/4671193/multi_uav_launch.zip)

**Comment by julianoes** [comment]
@Jaeyoung-Lim didn't we address this recently?

**Comment by Jaeyoung-Lim** [comment]
@julianoes Yes we did, but more than 10 uavs the offboard remote udp port is fixed in `14549` as in https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d-posix/rcS#L112

**Comment by robin-shaun** [comment]
Hello, I think the problem hasn't be solved. My rcS is the newest version. You said without using roslaunch, but I think the problem is the connection to mavros. In fact qgc can connect to more than 10 vehicles, but mavros cannot.
![1](https://user-images.githubusercontent.com/20561850/82986505-8775c600-a028-11ea-98fc-71d755ef9a11.jpg)

```
robin@robin-G3-3590:~/px4$ rostopic echo /iris_11/mavros/state
header: 
  seq: 0
  stamp: 
    secs: 2
    nsecs: 534000000
  frame_id: ''
connected: False
armed: False
guided: False
manual_input: False
mode: ''
system_status: 0
---
```
