### ISSUE TITLE
Battery Status working in uORB but not MAVLINK

### ISSUE THREAD

**Issue by lennartalff** [PX4/Firmware#15946]
**Describe the bug**
If inspecting the `battery_status` in uORB via the Mavlink Console by entering `listener battery_status` I seem to get reasonable messages. (See attached screenshot)

But in QGroundControl the voltage won't show up. If inspecting the MAVLINK messages in either QGroundControl or Mavros the voltage fields are not filled correctly.

**To Reproduce**
1. Using current  PX4 Firmware master (11.10.20) and nightly build of QGC (11.10.20)
2. Power on the Pixhawk4 and the connected Companion Computer (Raspberry Pi 4)
3. Use QGC, Mavros or the listener command in the nsh to inspect the battery status messages.

**Expected behavior**
I expect the measured voltages in the uORB topic to show up in the mavlink message as well.

**Log Files and Screenshots**
![uORB](https://user-images.githubusercontent.com/33184858/95751132-70b1d200-0c9e-11eb-9c4f-cbc6d116f6f2.png)
Mavros output of `rostopic echo /mavros/battery`:
```
header: 
  seq: 264
  stamp: 
    secs: 1602507969
    nsecs: 374154916
  frame_id: ''
voltage: 65.5350036621
current: 0.00999999977648
charge: nan
capacity: nan
design_capacity: nan
percentage: -0.00999999977648
power_supply_status: 2
power_supply_health: 0
power_supply_technology: 3
present: True
cell_voltage: []
location: "id0"
serial_number: ''
---
header: 
  seq: 265
  stamp: 
    secs: 1602507969
    nsecs: 377436515
  frame_id: ''
voltage: 65.5350036621
current: 0.00999999977648
charge: nan
capacity: nan
design_capacity: nan
percentage: -0.00999999977648
power_supply_status: 2
power_supply_health: 0
power_supply_technology: 3
present: True
cell_voltage: []
location: "id1"
serial_number: ''
---

```

![mavlink_inspector](https://user-images.githubusercontent.com/33184858/95751361-ce461e80-0c9e-11eb-8483-8446915eb0cd.png)
