### ISSUE TITLE
How to resolve FCU lpe mocap timeout 

### ISSUE THREAD

**Issue by pchatrath** [PX4/Firmware#5174]
I am using Optitrack Mocap system for getting position data. I run mavros and get position updates. However I get 
FCU: [lpe] mocap timeout
xy timeout 
sonar timeout 
msgs due to which local position keeps on initializing again and again. 

I tried streaming mocap data at 240FPS/300FPS i get same error. The frequency of /mavros/mocap/topic is around 350Hz. What am I missing?

**Comment by mhkabir** [comment]
what's the link you're using to the flight controller?

**Comment by pchatrath** [comment]
MavROS ttyUSB0@921600 with mavros_extra mocap_position_estimate

I do roslaunch mavros px4.launch fcu_url:=/dev/ttyUSB0:921600

**Comment by mhkabir** [comment]
Can you check if your timestamping is correct on the mocap data?

**Comment by pchatrath** [comment]
Does correct mean secs and nsecs are changing/increasing?

**Comment by mhkabir** [comment]
They need to be correctly time stamped with reference to the ROS clock. Mavros should handle the sync between the flight controller and ROS.

**Comment by pchatrath** [comment]
How do I verify if the timestamp are correct with reference to ROS clock?

**Comment by pchatrath** [comment]
@mhkabir  If I connect my laptop which is running ROS MASTER everything is fine - the timestamps are correct ( increasing). However when I connect my Odroid to my laptop by setting ROS_MASTER_URI the timestamps are not strictly increasing -  for eg i see timestamp with nsecs 50 after timestamp.nsecs 200. 

I installed chrony to time synchronization but it didnt help. Any idea how I can get timestamps in correct order from one ROS computer to another

**Comment by pchatrath** [comment]
Timestamp:

` seq: 27104                                                            
  stamp:                                                                
    secs: 1469984240                                                    │
    nsecs: 483485794                                                    │
  frame_id: world                                                       │
pose:                                                                   │
  position:                                                             │
    x: -4.08432912827                                                   │
    y: 3.941188097                                                      │
    z: 0.978130221367                                                   │
  orientation:                                                          │
    x: 0.0128829134628                                                  │
    y: -0.00318198255263                                                │
    z: 0.537988424301                                                   │
    w: 0.842847764492                                                   │
---                                                                     │
header:                                                                 │
  seq: 27105                                                            │
  stamp:                                                                │
    secs: 1469984240                                                    │
    nsecs: 483973148                                                    │
  frame_id: world                                                       │
pose:                                                                   │
  position:                                                             │
    x: -4.08432912827                                                   │
    y: 3.941188097                                                      │
    z: 0.978130221367                                                   │
  orientation:                                                          │
    x: 0.0128829134628                                                  │
    y: -0.00318198255263                                                │
    z: 0.537988424301                                                   │
    w: 0.842847764492`

**Comment by pchatrath** [comment]
Timestamp

 seq: 27104                                                            
  stamp:                                                                
    secs: 1469984240                                                    │
    nsecs: 483485794                                                    │
  frame_id: world                                                       │
pose:                                                                   │
  position:                                                             │
    x: -4.08432912827                                                   │
    y: 3.941188097                                                      │
    z: 0.978130221367                                                   │
  orientation:                                                          │
    x: 0.0128829134628                                                  │
    y: -0.00318198255263                                                │
    z: 0.537988424301                                                   │
    w: 0.842847764492                                                   │
---                                                                     │
header:                                                                 │
  seq: 27105                                                            │
  stamp:                                                                │
    secs: 1469984240                                                    │
    nsecs: 483973148                                                    │
  frame_id: world                                                       │
pose:                                                                   │
  position:                                                             │
    x: -4.08432912827                                                   │
    y: 3.941188097                                                   
    z: 0.978130221367                                             
  orientation:                                                          
    x: 0.0128829134628                                                  
    y: -0.00318198255263                                               
    z: 0.537988424301                                                   
    w: 0.842847764492

**Comment by pchatrath** [comment]
rostopic echo -n1 /diagnostics output from odroid
```
header: 
  seq: 1087
  stamp: 
    secs: 1469989787
    nsecs: 109486582
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Received packets:
        value: 37618
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 185
      - 
        key: Tx sequence number:
        value: 79
      - 
        key: Rx total bytes:
        value: 22674182
      - 
        key: Tx total bytes:
        value: 12855934
      - 
        key: Rx speed:
        value: 24092.000000
      - 
        key: Tx speed:
        value: 14006.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: 99.99
      - 
        key: EPV (m)
        value: 99.99
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Heartbeats since startup
        value: 1454
      - 
        key: Frequency (Hz)
        value: 1.037044
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: PX4
      - 
        key: Mode
        value: ALTCTL
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Sensor present
        value: 0x00000040
      - 
        key: Sensor enabled
        value: 0x00000040
      - 
        key: Sensor helth
        value: 0x00000040
      - 
        key: Sensor Optical Flow
        value: Ok
      - 
        key: CPU Load (%)
        value: 67.9
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Voltage
        value: 11.33
      - 
        key: Current
        value: 0.2
      - 
        key: Remaining
        value: 58.0
  - 
    level: 0
    name: mavros: Time Sync
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Timesyncs since startup
        value: 14472
      - 
        key: Frequency (Hz)
        value: 10.000029
      - 
        key: Last dt (ms)
        value: 0.479080
      - 
        key: Mean dt (ms)
        value: 0.006260
      - 
        key: Last system time (s)
        value: 14255.060253000
      - 
        key: Time offset (s)
        value: 1469975531.952977896
```
